twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - 'form/fields.html.twig'
    globals:
        # Передаем переменную proflies из services.yaml для того чтобы она была доступна во всем шаблоне
        profiles: '%profiles%'


when@test:
    twig:
        strict_variables: true
